# Required to run your project under the correct environment.
language: php

php:
- '5.4'

services:
  - mysql

before_script:
  - composer require phpunit/phpunit
  - mysql -u root -e 'CREATE DATABASE soen;'
  - mysql -u root soen < soen.sql
  
script: phpunit --configuration phpunit.xml --coverage-text