-- MySQL Script generated by MySQL Workbench
-- 03/22/17 23:17:41
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema soen
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema soen
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `soen` DEFAULT CHARACTER SET utf8 ;
USE `soen` ;

-- -----------------------------------------------------
-- Table `soen`.`Rights`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soen`.`Rights` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


--
-- Dumping data for table `rights`
--

LOCK TABLES `rights` WRITE;
INSERT INTO `rights` VALUES (1,'teacher'),(2,'student');
UNLOCK TABLES;


-- -----------------------------------------------------
-- Table `soen`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soen`.`User` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NULL,
  `passwordMD5` VARCHAR(255) NULL,
  `user` VARCHAR(45) NULL,
  `Rights_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `rights_id_idx` (`Rights_id` ASC),
  CONSTRAINT `rights_id`
    FOREIGN KEY (`Rights_id`)
    REFERENCES `soen`.`Rights` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `soen`.`Course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soen`.`Course` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `description` TEXT NULL,
  `User_id` INT NULL COMMENT 'Contains the name of the creator of the course',
  PRIMARY KEY (`id`),
  INDEX `fk_Course_User1_idx` (`User_id` ASC),
  CONSTRAINT `fk_Course_User1`
    FOREIGN KEY (`User_id`)
    REFERENCES `soen`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `soen`.`CourseUser`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soen`.`CourseUser` (
  `User_id` INT NOT NULL,
  `Course_id` INT NOT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`),
  INDEX `course_id_idx` (`Course_id` ASC),
  CONSTRAINT `id`
    FOREIGN KEY (`User_id`)
    REFERENCES `soen`.`User` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `course_id`
    FOREIGN KEY (`Course_id`)
    REFERENCES `soen`.`Course` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `soen`.`Announcements`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soen`.`Announcements` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Course_id` INT NULL,
  `User_id` INT NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `User_id_idx` (`User_id` ASC),
  CONSTRAINT `fk_course_id`
    FOREIGN KEY (`Course_id`)
    REFERENCES `soen`.`Course` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_user_id`
    FOREIGN KEY (`User_id`)
    REFERENCES `soen`.`User` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `soen`.`Quiz`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soen`.`Quiz` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `date` DATE NULL,
  `Course_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Quiz_Course1_idx` (`Course_id` ASC),
  CONSTRAINT `fk_Quiz_Course1`
    FOREIGN KEY (`Course_id`)
    REFERENCES `soen`.`Course` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `soen`.`QuizQuestion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soen`.`QuizQuestion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `question` VARCHAR(45) NULL,
  `prop1` VARCHAR(45) NULL,
  `prop2` VARCHAR(45) NULL,
  `prop3` VARCHAR(45) NULL,
  `prop4` VARCHAR(45) NULL,
  `prop5` VARCHAR(45) NULL,
  `ans` INT NULL,
  `Quiz_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_QuizQuestion_Quiz1_idx` (`Quiz_id` ASC),
  CONSTRAINT `fk_QuizQuestion_Quiz1`
    FOREIGN KEY (`Quiz_id`)
    REFERENCES `soen`.`Quiz` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `soen`.`QuizAnswerStudent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soen`.`QuizAnswerStudent` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `QuizQuestion_id` INT NOT NULL,
  `User_id` INT NULL,
  `answer` INT NULL,
  `Quiz_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_quiz_question_idx` (`QuizQuestion_id` ASC),
  INDEX `fk_quiz_user_idx` (`User_id` ASC),
  INDEX `fk_QuizAnswerStudent_Quiz1_idx` (`Quiz_id` ASC),
  CONSTRAINT `fk_quiz_question`
    FOREIGN KEY (`QuizQuestion_id`)
    REFERENCES `soen`.`QuizQuestion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_quiz_user`
    FOREIGN KEY (`User_id`)
    REFERENCES `soen`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_QuizAnswerStudent_Quiz1`
    FOREIGN KEY (`Quiz_id`)
    REFERENCES `soen`.`Quiz` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `soen`.`QuizStudent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soen`.`QuizStudent` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `submitted` TINYINT NULL DEFAULT 0,
  `User_id` INT NOT NULL,
  `Quiz_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_QuizStudent_User1_idx` (`User_id` ASC),
  INDEX `fk_QuizStudent_Quiz1_idx` (`Quiz_id` ASC),
  CONSTRAINT `fk_QuizStudent_User1`
    FOREIGN KEY (`User_id`)
    REFERENCES `soen`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_QuizStudent_Quiz1`
    FOREIGN KEY (`Quiz_id`)
    REFERENCES `soen`.`Quiz` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
